/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as VendorSettingsRouteImport } from './routes/vendor.settings'
import { Route as VendorProductsRouteImport } from './routes/vendor.products'
import { Route as VendorOrdersRouteImport } from './routes/vendor.orders'
import { Route as VendorDashboardRouteImport } from './routes/vendor.dashboard'
import { Route as RiderDashboardRouteImport } from './routes/rider.dashboard'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as AdminVendorsRouteImport } from './routes/admin.vendors'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminRidersRouteImport } from './routes/admin.riders'
import { Route as AdminDisputesRouteImport } from './routes/admin.disputes'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorSettingsRoute = VendorSettingsRouteImport.update({
  id: '/vendor/settings',
  path: '/vendor/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorProductsRoute = VendorProductsRouteImport.update({
  id: '/vendor/products',
  path: '/vendor/products',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorOrdersRoute = VendorOrdersRouteImport.update({
  id: '/vendor/orders',
  path: '/vendor/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorDashboardRoute = VendorDashboardRouteImport.update({
  id: '/vendor/dashboard',
  path: '/vendor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderDashboardRoute = RiderDashboardRouteImport.update({
  id: '/rider/dashboard',
  path: '/rider/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVendorsRoute = AdminVendorsRouteImport.update({
  id: '/admin/vendors',
  path: '/admin/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/admin/students',
  path: '/admin/students',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRidersRoute = AdminRidersRouteImport.update({
  id: '/admin/riders',
  path: '/admin/riders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/admin/disputes',
  path: '/admin/disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/mcp': typeof McpRoute
  '/profile': typeof ProfileRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/riders': typeof AdminRidersRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$id': typeof ProductIdRoute
  '/rider/dashboard': typeof RiderDashboardRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/products': typeof VendorProductsRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/orders/': typeof OrdersIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/mcp': typeof McpRoute
  '/profile': typeof ProfileRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/riders': typeof AdminRidersRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$id': typeof ProductIdRoute
  '/rider/dashboard': typeof RiderDashboardRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/products': typeof VendorProductsRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/orders': typeof OrdersIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/mcp': typeof McpRoute
  '/profile': typeof ProfileRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/disputes': typeof AdminDisputesRoute
  '/admin/riders': typeof AdminRidersRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$id': typeof ProductIdRoute
  '/rider/dashboard': typeof RiderDashboardRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/products': typeof VendorProductsRoute
  '/vendor/settings': typeof VendorSettingsRoute
  '/orders/': typeof OrdersIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/mcp'
    | '/profile'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/disputes'
    | '/admin/riders'
    | '/admin/students'
    | '/admin/vendors'
    | '/orders/$id'
    | '/product/$id'
    | '/rider/dashboard'
    | '/vendor/dashboard'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/settings'
    | '/orders/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/mcp'
    | '/profile'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/disputes'
    | '/admin/riders'
    | '/admin/students'
    | '/admin/vendors'
    | '/orders/$id'
    | '/product/$id'
    | '/rider/dashboard'
    | '/vendor/dashboard'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/settings'
    | '/orders'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/mcp'
    | '/profile'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/disputes'
    | '/admin/riders'
    | '/admin/students'
    | '/admin/vendors'
    | '/orders/$id'
    | '/product/$id'
    | '/rider/dashboard'
    | '/vendor/dashboard'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/settings'
    | '/orders/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  McpRoute: typeof McpRoute
  ProfileRoute: typeof ProfileRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDisputesRoute: typeof AdminDisputesRoute
  AdminRidersRoute: typeof AdminRidersRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminVendorsRoute: typeof AdminVendorsRoute
  OrdersIdRoute: typeof OrdersIdRoute
  ProductIdRoute: typeof ProductIdRoute
  RiderDashboardRoute: typeof RiderDashboardRoute
  VendorDashboardRoute: typeof VendorDashboardRoute
  VendorOrdersRoute: typeof VendorOrdersRoute
  VendorProductsRoute: typeof VendorProductsRoute
  VendorSettingsRoute: typeof VendorSettingsRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/settings': {
      id: '/vendor/settings'
      path: '/vendor/settings'
      fullPath: '/vendor/settings'
      preLoaderRoute: typeof VendorSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/products': {
      id: '/vendor/products'
      path: '/vendor/products'
      fullPath: '/vendor/products'
      preLoaderRoute: typeof VendorProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/orders': {
      id: '/vendor/orders'
      path: '/vendor/orders'
      fullPath: '/vendor/orders'
      preLoaderRoute: typeof VendorOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/dashboard': {
      id: '/vendor/dashboard'
      path: '/vendor/dashboard'
      fullPath: '/vendor/dashboard'
      preLoaderRoute: typeof VendorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/dashboard': {
      id: '/rider/dashboard'
      path: '/rider/dashboard'
      fullPath: '/rider/dashboard'
      preLoaderRoute: typeof RiderDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vendors': {
      id: '/admin/vendors'
      path: '/admin/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AdminVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/riders': {
      id: '/admin/riders'
      path: '/admin/riders'
      fullPath: '/admin/riders'
      preLoaderRoute: typeof AdminRidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/admin/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  McpRoute: McpRoute,
  ProfileRoute: ProfileRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDisputesRoute: AdminDisputesRoute,
  AdminRidersRoute: AdminRidersRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminVendorsRoute: AdminVendorsRoute,
  OrdersIdRoute: OrdersIdRoute,
  ProductIdRoute: ProductIdRoute,
  RiderDashboardRoute: RiderDashboardRoute,
  VendorDashboardRoute: VendorDashboardRoute,
  VendorOrdersRoute: VendorOrdersRoute,
  VendorProductsRoute: VendorProductsRoute,
  VendorSettingsRoute: VendorSettingsRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
